version: '3.9'

services:
  frp:
    image: ghcr.io/nekoluka/frp-docker:main
    volumes:
      - ./frp_default.ini:/frp.ini
    environment:
      - FRP_CONFIG_FILE=/frp.ini
      - FRP_VERSION=0.51.3
